services:
  scheduleapplication:
    container_name: scheduleapplication
    image: leonardosantino/scheduleapplication:0.0.2
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - scheduledatabase
    environment:
      # SPRING
      SPRING_PROFILES_ACTIVE: dev
      SPRING_MONGODB_URI: mongodb://schedule:XaY2cMuXdJ4I7aJA@scheduledatabase:27017/schedule
      # AWS
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:

  scheduledatabase:
    container_name: scheduledatabase
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: schedule
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: XaY2cMuXdJ4I7aJA
    volumes:
      - schedule_database_data:/data/db
      - schedule_database_config:/data/configdb

volumes:
  schedule_database_data:
    name: schedule_database_data
  schedule_database_config:
    name: schedule_database_config

networks:
  default:
    name: schedule_default