services:
  schedule_application:
    container_name: schedule_application
    image: leonardosantino/schedule_application:0.0.1
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - schedule_database
    environment:
      # SPRING
      SPRING_PROFILES_ACTIVE: dev
      SPRING_MONGODB_URI: mongodb://local:XaY2cMuXdJ4I7aJA@schedule_database:27017/schedule

  schedule_database:
    container_name: schedule_database
    image: mongo:8.3.7
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      # USER
      MONGO_INITDB_DATABASE: schedule
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: XaY2cMuXdJ4I7aJA
