spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schedule
    username: local
    password: XaY2cMuXdJ4I7aJA
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
