spring:
  config:
    import: aws-secretsmanager:agendily
  mongodb:
    uri: ${asm.mongodb.uri}


aws:
  cognito:
    userPoolId: us-east-1_0zpeIuMMO

vapid:
  publicKey: BAVOkJ33u7oGJeyllbqzklPmdcezdFvBbMwmvr6P0BknoawPAMoRpOZplSdHh1C2kArm3uiQ22932Am-Qke9RJM
  privateKey: ${asm.vapid.privateKey}
  subject: mailto:softxre@googlegroups.com
